version: '3'
services:
  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - $PWD/.redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - $PWD/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: itreallytiedtheroomtogether
      POSTGRES_USER: localdev
      POSTGRES_DB: stonks
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    hostname: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
