version: '3'
services:
  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - $PWD/.redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - stonknet
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - $PWD/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: itreallytiedtheroomtogether
      POSTGRES_USER: localdev
      POSTGRES_DB: stonks
    networks:
      - stonknet
  adminer:
    image: adminer
    hostname: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - stonknet
  app:
    image: stonksapp:local
    container_name: stonks_app
    tty: true
    build:
      context: .
      dockerfile: $PWD/.docker/dev/Dockerfile
    volumes:
      - stonksapp-sync:/app:nocopy
    networks:
      - stonknet
    ports:
      - '4000:4000'

volumes:
  # This is for the docker-sync container that gets started
  stonksapp-sync:
    external: true

networks:
  stonknet:
