export const SKIN_DEFAULTS = [
  {
    id: 'GOLD_LIGHTER',
    previewColor: '#fff9d2',
    hue: 10,
    saturation: 108,
    lightness: 160,
    contrast: 41,
  },
  {
    id: 'GOLD_LIGHT',
    previewColor: '#fff3b1',
    hue: 2,
    saturation: 145,
    lightness: 144,
    contrast: 65,
  },
  {
    id: 'GOLD',
    previewColor: '#ffd97e',
    hue: 6,
    saturation: 167,
    lightness: 118,
    contrast: 86,
  },
  {
    id: 'GOLD_DARK',
    previewColor: '#fbc64f',
    hue: 6,
    saturation: 182,
    lightness: 96,
    contrast: 121,
  },
  {
    id: 'BEIGE_LIGHTER',
    previewColor: '#ffdad0',
    hue: -26,
    saturation: 114,
    lightness: 146,
    contrast: 41,
  },
  {
    id: 'BEIGE_LIGHT',
    previewColor: '#ffd1ce',
    hue: -34,
    saturation: 168,
    lightness: 139,
    contrast: 52,
  },
  {
    id: 'BEIGE',
    previewColor: '#f9b3ad',
    hue: -32,
    saturation: 100,
    lightness: 94,
    contrast: 112,
  },
  {
    id: 'BROWN_LIGHTER',
    previewColor: '#e5ab75',
    hue: 0,
    saturation: 124,
    lightness: 87,
    contrast: 109,
  },
  {
    id: 'BROWN_LIGHT',
    previewColor: '#c88c52',
    hue: 0,
    saturation: 157,
    lightness: 76,
    contrast: 99,
  },
  {
    id: 'BROWN',
    previewColor: '#976c40',
    hue: 0,
    saturation: 157,
    lightness: 57,
    contrast: 104,
  },
  {
    id: 'BURGUNDY_LIGHT',
    previewColor: '#ab706a',
    hue: -32,
    saturation: 183,
    lightness: 64,
    contrast: 108,
  },
  {
    id: 'BURGUNDY',
    previewColor: '#7d5248',
    hue: -26,
    saturation: 164,
    lightness: 47,
    contrast: 101,
  },
  {
    id: 'BLACK_LIGHT',
    previewColor: '#402726',
    hue: -32,
    saturation: 173,
    lightness: 24,
    contrast: 91,
  },
  {
    id: 'BLACK_DARKER',
    previewColor: '#170f0e',
    hue: -32,
    saturation: 157,
    lightness: 9,
    contrast: 90,
  },
]
