export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_FIELD = 'INVALID_FIELD',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  USER_NOT_IN_GAME = 'USER_NOT_IN_GAME',
  USER_ALREADY_IN_GAME = 'USER_ALREADY_IN_GAME',
}
