export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_FIELD = 'INVALID_FIELD',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  USER_NOT_IN_GAME = 'USER_NOT_IN_GAME',
  INVALID_GAME_CODE = 'INVALID_GAME_CODE',
  USER_ALREADY_IN_GAME = 'USER_ALREADY_IN_GAME',
  GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
  SESSION_ID_NOT_SET = 'SESSION_ID_NOT_SET',
}
