version: '3'
services:
  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server
    volumes:
      - $PWD/.redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - stonknet
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - $PWD/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: itreallytiedtheroomtogether
      POSTGRES_USER: localdev
      POSTGRES_DB: stonks
    networks:
      - stonknet
  app:
    image: stonksapp:dev
    build:
      context: .
      dockerfile: $PWD/.docker/prod/Dockerfile
    networks:
      - stonknet
    ports:
      - '4000:4000'

volumes:
  # This is for the docker-sync container that gets started
  stonksapp-sync:
    external: true

networks:
  stonknet:
